import { cookies } from "next/headers";

export type Locale = "en" | "es";

export const services = [
  { slug: "automation-software", key: "nav_automation", group: "nav_digital" },
  { slug: "system-integrations", key: "nav_integrations", group: "nav_digital" },
  { slug: "analytics-dashboards", key: "nav_data", group: "nav_digital" },
  { slug: "ai-automation", key: "nav_ai", group: "nav_digital" },
  { slug: "process-optimization", key: "nav_process", group: "nav_digital" },
  { slug: "managed-technical-support", key: "nav_support", group: "nav_infra" },
  { slug: "enterprise-help-desk", key: "nav_helpdesk", group: "nav_infra" },
  { slug: "monitoring-continuity", key: "nav_monitoring", group: "nav_infra" },
  { slug: "cloud-servers", key: "nav_cloud", group: "nav_infra" },
  { slug: "contact-center-cx", key: "nav_cx", group: "nav_customer" },
  { slug: "omnichannel-service", key: "nav_omnichannel", group: "nav_customer" },
  { slug: "quality-audit", key: "nav_quality", group: "nav_customer" },
  { slug: "crm-sales-workflows", key: "nav_crm", group: "nav_customer" },
  { slug: "operational-back-office", key: "nav_backoffice", group: "nav_operations" },
  { slug: "administrative-bpo", key: "nav_bpo", group: "nav_operations" },
  { slug: "operational-reporting", key: "nav_reporting", group: "nav_operations" },
  { slug: "managed-operations", key: "nav_operations", group: "nav_operations" },
] as const;

export const industries = [
  { slug: "healthcare", key: "nav_health" },
  { slug: "banking-finance", key: "nav_finance" },
  { slug: "retail", key: "nav_retail" },
  { slug: "telecom", key: "nav_telecom" },
  { slug: "travel", key: "nav_travel" },
] as const;

export const dictionaries = {
  en: {
    nav_services: "Services",
    nav_sectors: "Industries",
    nav_company: "Company",
    nav_contact: "Contact",
    nav_service_intro: "Solutions to modernize critical operations, customer service, and enterprise technology.",
    nav_service_cta: "Explore services",
    nav_digital: "Digital transformation",
    nav_operations: "Managed operations",
    nav_customer: "Customer experience",
    nav_infra: "Infrastructure and support",
    nav_automation: "Automation and software",
    nav_integrations: "System integrations",
    nav_data: "Analytics and dashboards",
    nav_ai: "AI automation",
    nav_support: "Managed technical support",
    nav_helpdesk: "Enterprise help desk",
    nav_monitoring: "Monitoring and continuity",
    nav_cloud: "Cloud and servers",
    nav_cx: "Contact center and CX",
    nav_omnichannel: "Omnichannel service",
    nav_quality: "Quality and audit",
    nav_crm: "CRM and sales workflows",
    nav_backoffice: "Operational back office",
    nav_bpo: "Administrative BPO",
    nav_process: "Process optimization",
    nav_reporting: "Operational reporting",
    nav_industries: "Industries",
    nav_health: "Healthcare",
    nav_finance: "Banking and finance",
    nav_retail: "Retail",
    nav_telecom: "Telecom",
    nav_travel: "Travel",
    cta: "Start assessment",
    hero_badge: "Enterprise technology partner",
    hero_title: "Precision systems for enterprise operations",
    hero_title_line_1: "Precision systems",
    hero_title_line_2: "for enterprise operations",
    hero_desc: "CQuest builds and operates digital systems for teams that need reliable workflows, clear data, and continuous technical support.",
    hero_proof_1: "Systems",
    hero_proof_2: "Operations",
    hero_proof_3: "Continuity",
    hero_visual_label: "Enterprise operating system",
    hero_visual_status: "Live delivery",
    hero_capability_1_label: "Digital transformation",
    hero_capability_1_title: "Modernize critical workflows",
    hero_capability_1_desc: "Automations, integrations, dashboards, and AI-enabled processes designed around measurable execution.",
    hero_capability_2_label: "Managed operations",
    hero_capability_2_title: "Operate with continuity",
    hero_capability_2_desc: "Technical support, monitoring, back-office execution, and service management for teams that cannot stop.",
    hero_capability_3_label: "Customer experience",
    hero_capability_3_title: "Scale service quality",
    hero_capability_3_desc: "Contact center, omnichannel workflows, CRM operations, and quality controls under one delivery model.",
    services_title: "Core services",
    home_services_kicker: "Integrated capabilities",
    home_services_title: "One partner for the systems your operation depends on",
    home_services_summary: "CQuest connects software delivery, infrastructure support, customer operations, and reporting into a managed model built for execution.",
    home_service_1_title: "Automation and AI workflows",
    home_service_1_desc: "Replace repetitive work with integrations, orchestration, and AI-assisted processes that reduce manual handoffs.",
    home_service_2_title: "Managed technical support",
    home_service_2_desc: "Centralize monitoring, help desk, escalation, continuity, and infrastructure operations with clear service ownership.",
    home_service_3_title: "Customer experience operations",
    home_service_3_desc: "Run contact center, CRM, omnichannel service, quality, and audit workflows with consistent visibility.",
    home_service_4_title: "Operational intelligence",
    home_service_4_desc: "Turn process data into dashboards, scorecards, and management views that make performance easier to control.",
    home_service_5_title: "System integrations",
    home_service_5_desc: "Connect CRMs, ERPs, help desks, cloud tools, and internal platforms into cleaner operational workflows.",
    home_service_6_title: "Cloud and infrastructure operations",
    home_service_6_desc: "Support servers, environments, access, deployments, and continuity practices for teams that need stable technology.",
    home_service_7_title: "Process optimization",
    home_service_7_desc: "Map bottlenecks, remove duplicated work, and redesign execution flows around measurable service outcomes.",
    home_service_8_title: "Enterprise help desk",
    home_service_8_desc: "Operate structured intake, triage, escalation, documentation, and resolution tracking for internal teams.",
    home_service_9_title: "CRM and sales workflows",
    home_service_9_desc: "Improve lead handling, customer follow-up, pipeline visibility, and service-to-sales coordination.",
    home_service_10_title: "Back-office operations",
    home_service_10_desc: "Run administrative, reporting, documentation, and operational support tasks under a managed delivery model.",
    home_method_kicker: "Delivery model",
    home_method_title: "Designed, deployed, and operated with enterprise discipline",
    home_method_summary: "We move from diagnosis to implementation with a practical operating rhythm: map the process, stabilize the system, automate the work, and report the outcomes.",
    home_method_1: "Diagnose the current operation",
    home_method_2: "Design the target workflow",
    home_method_3: "Deploy the technology layer",
    home_method_4: "Operate, measure, and improve",
    home_industries_kicker: "High-demand industries",
    home_industries_title: "Built for teams where service continuity matters",
    home_industries_summary: "Healthcare, finance, retail, telecom, and travel teams use CQuest-style delivery when operations need speed, control, and a dependable service model.",
    home_outcome_1: "Fewer manual escalations",
    home_outcome_2: "Clearer operational ownership",
    home_outcome_3: "Better customer response visibility",
    home_cta_title: "Ready to modernize a critical operation?",
    home_cta_summary: "Start with a focused assessment. We identify the highest-impact workflows, the systems involved, and the managed model needed to improve them.",
    services_page_summary: "A modular portfolio for companies that need technology, operational control, and measurable execution.",
    service_page_summary: "A focused CQuest solution designed to improve execution, visibility, and service continuity.",
    industries_page_summary: "Technology and managed operations adapted to high-demand industries.",
    industry_page_summary: "CQuest aligns technology, process, and service delivery for this industry.",
    company_page_title: "A technology partner built for operational growth",
    company_page_summary: "CQuest combines software, infrastructure, support, and managed operations to help organizations scale with control.",
    contact_page_title: "Start a technology assessment",
    contact_page_summary: "Tell us what you need to improve, automate, or operate. Our team will route the conversation to the right specialist.",
    back_home: "Back to home",
    kpi_1: "Active projects",
    kpi_2: "Operational uptime",
    kpi_3: "Average response time",
    footer: "CQuest. Technology solutions for controlled growth.",
  },
  es: {
    nav_services: "Servicios",
    nav_sectors: "Sectores",
    nav_company: "Empresa",
    nav_contact: "Contacto",
    nav_service_intro: "Soluciones para modernizar operaciones criticas, atencion al cliente y tecnologia empresarial.",
    nav_service_cta: "Explorar servicios",
    nav_digital: "Transformacion digital",
    nav_operations: "Operaciones gestionadas",
    nav_customer: "Experiencia de cliente",
    nav_infra: "Infraestructura y soporte",
    nav_automation: "Automatizacion y software",
    nav_integrations: "Integraciones de sistemas",
    nav_data: "Analitica y dashboards",
    nav_ai: "Automatizacion con IA",
    nav_support: "Soporte tecnico gestionado",
    nav_helpdesk: "Mesa de ayuda empresarial",
    nav_monitoring: "Monitoreo y continuidad",
    nav_cloud: "Cloud y servidores",
    nav_cx: "Contact center y CX",
    nav_omnichannel: "Atencion omnicanal",
    nav_quality: "Calidad y auditoria",
    nav_crm: "CRM y flujos comerciales",
    nav_backoffice: "Back office operativo",
    nav_bpo: "BPO administrativo",
    nav_process: "Optimizacion de procesos",
    nav_reporting: "Reporteria operativa",
    nav_industries: "Industrias",
    nav_health: "Salud",
    nav_finance: "Banca y finanzas",
    nav_retail: "Retail",
    nav_telecom: "Telecom",
    nav_travel: "Turismo",
    cta: "Iniciar diagnostico",
    hero_badge: "Socio tecnologico empresarial",
    hero_title: "Tecnologia para operaciones precisas",
    hero_title_line_1: "Tecnologia para",
    hero_title_line_2: "operaciones precisas",
    hero_desc: "CQuest crea y opera sistemas digitales para equipos que necesitan flujos confiables, datos claros y soporte tecnico continuo.",
    hero_proof_1: "Sistemas",
    hero_proof_2: "Operaciones",
    hero_proof_3: "Continuidad",
    hero_visual_label: "Sistema operativo empresarial",
    hero_visual_status: "Entrega activa",
    hero_capability_1_label: "Transformacion digital",
    hero_capability_1_title: "Modernizar flujos criticos",
    hero_capability_1_desc: "Automatizaciones, integraciones, dashboards y procesos con IA disenados alrededor de ejecucion medible.",
    hero_capability_2_label: "Operaciones gestionadas",
    hero_capability_2_title: "Operar con continuidad",
    hero_capability_2_desc: "Soporte tecnico, monitoreo, back office y gestion de servicio para equipos que no pueden detenerse.",
    hero_capability_3_label: "Experiencia de cliente",
    hero_capability_3_title: "Escalar la calidad del servicio",
    hero_capability_3_desc: "Contact center, flujos omnicanal, operaciones CRM y controles de calidad bajo un solo modelo de entrega.",
    services_title: "Servicios clave",
    home_services_kicker: "Capacidades integradas",
    home_services_title: "Un solo socio para los sistemas de los que depende tu operacion",
    home_services_summary: "CQuest conecta desarrollo de software, soporte de infraestructura, operaciones de cliente y reportería en un modelo gestionado creado para ejecutar.",
    home_service_1_title: "Automatizacion y flujos con IA",
    home_service_1_desc: "Reemplaza trabajo repetitivo con integraciones, orquestacion y procesos asistidos por IA que reducen traspasos manuales.",
    home_service_2_title: "Soporte tecnico gestionado",
    home_service_2_desc: "Centraliza monitoreo, mesa de ayuda, escalamiento, continuidad y operaciones de infraestructura con propiedad clara del servicio.",
    home_service_3_title: "Operaciones de experiencia de cliente",
    home_service_3_desc: "Opera contact center, CRM, atencion omnicanal, calidad y auditoria con visibilidad consistente.",
    home_service_4_title: "Inteligencia operativa",
    home_service_4_desc: "Convierte datos de procesos en dashboards, scorecards y vistas gerenciales que facilitan controlar el rendimiento.",
    home_service_5_title: "Integraciones de sistemas",
    home_service_5_desc: "Conecta CRMs, ERPs, mesas de ayuda, herramientas cloud y plataformas internas en flujos operativos mas claros.",
    home_service_6_title: "Operaciones cloud e infraestructura",
    home_service_6_desc: "Soporta servidores, ambientes, accesos, despliegues y practicas de continuidad para equipos que necesitan tecnologia estable.",
    home_service_7_title: "Optimizacion de procesos",
    home_service_7_desc: "Mapea cuellos de botella, elimina trabajo duplicado y rediseña flujos de ejecucion alrededor de resultados medibles.",
    home_service_8_title: "Mesa de ayuda empresarial",
    home_service_8_desc: "Opera recepcion, triaje, escalamiento, documentacion y seguimiento de resolucion para equipos internos.",
    home_service_9_title: "CRM y flujos comerciales",
    home_service_9_desc: "Mejora gestion de leads, seguimiento comercial, visibilidad de pipeline y coordinacion entre servicio y ventas.",
    home_service_10_title: "Operaciones back-office",
    home_service_10_desc: "Gestiona tareas administrativas, reporteria, documentacion y soporte operativo bajo un modelo de entrega gestionado.",
    home_method_kicker: "Modelo de entrega",
    home_method_title: "Disenado, implementado y operado con disciplina empresarial",
    home_method_summary: "Pasamos del diagnostico a la implementacion con un ritmo operativo practico: mapear el proceso, estabilizar el sistema, automatizar el trabajo y reportar resultados.",
    home_method_1: "Diagnosticar la operacion actual",
    home_method_2: "Disenar el flujo objetivo",
    home_method_3: "Implementar la capa tecnologica",
    home_method_4: "Operar, medir y mejorar",
    home_industries_kicker: "Industrias de alta demanda",
    home_industries_title: "Creado para equipos donde la continuidad del servicio importa",
    home_industries_summary: "Equipos de salud, finanzas, retail, telecom y turismo usan un modelo tipo CQuest cuando sus operaciones necesitan velocidad, control y entrega confiable.",
    home_outcome_1: "Menos escalaciones manuales",
    home_outcome_2: "Mayor claridad de responsables",
    home_outcome_3: "Mejor visibilidad de respuesta al cliente",
    home_cta_title: "Listo para modernizar una operacion critica?",
    home_cta_summary: "Empieza con un diagnostico enfocado. Identificamos los flujos de mayor impacto, los sistemas involucrados y el modelo gestionado necesario para mejorarlos.",
    services_page_summary: "Un portafolio modular para empresas que necesitan tecnologia, control operativo y ejecucion medible.",
    service_page_summary: "Una solucion CQuest enfocada en mejorar ejecucion, visibilidad y continuidad del servicio.",
    industries_page_summary: "Tecnologia y operaciones gestionadas adaptadas a industrias de alta demanda.",
    industry_page_summary: "CQuest alinea tecnologia, procesos y entrega de servicio para este sector.",
    company_page_title: "Un socio tecnologico para crecer con control operativo",
    company_page_summary: "CQuest combina software, infraestructura, soporte y operaciones gestionadas para ayudar a las organizaciones a escalar con control.",
    contact_page_title: "Iniciar un diagnostico tecnologico",
    contact_page_summary: "Cuentanos que necesitas mejorar, automatizar u operar. Nuestro equipo dirigira la conversacion al especialista correcto.",
    back_home: "Volver al inicio",
    kpi_1: "Proyectos activos",
    kpi_2: "Disponibilidad operativa",
    kpi_3: "Tiempo promedio de respuesta",
    footer: "CQuest. Soluciones tecnologicas para crecer con control.",
  },
} as const;

export type Dictionary = Record<string, string>;
export type DictionaryKey = keyof typeof dictionaries.en;

export async function getLocale(): Promise<Locale> {
  const cookieStore = await cookies();
  const locale = cookieStore.get("locale")?.value;

  return locale === "en" ? "en" : "es";
}

export async function getDictionary(): Promise<Dictionary> {
  return dictionaries[await getLocale()];
}

export function t(dictionary: Dictionary, key: string): string {
  return dictionary[key];
}
